### PR TITLE
Support the new variables resolver

### LINKED ISSUE #4: Support for serverless v3 variables resolver
Hello, thanks for this useful software! 

I noticed that `serverless-find-resource` does not work with Serverless v3, as it has changed its way to handle variable resolvers incompatibly in v3.
https://www.serverless.com/framework/docs/deprecations#new-variables-resolver

When I run `sls deploy` and `sls doctor` I get the following output:
```sh
$ sls deploy
Environment: darwin, node 16.9.1, framework 3.2.1 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Unrecognized configuration variable sources: ""

1 deprecation found: run 'serverless doctor' for more details

$ sls doctor
1 deprecation triggered in the last command:

Plugin "FindResourcePlugin" attempts to extend old variables resolver. Ensure to rely on latest version of a plugin and if this warning is still displayed please report the problem at plugin issue trackerStarting with next major release, old variables resolver will not be supported.

More info: https://serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
```

(For reference, [this patch](https://github.com/wktk/serverless-find-resource/commit/4e42e5e9ca47e9bebf0d8717dd2c39011f2af31e) works fine for me.  As I am new to Serverless and not sure if the patch is correct, I'm not opening a pull request, but feel free to import it if you would like to.)

### PR DESCRIPTION
**Pull request by wktk**
may close #4

### CODE REVIEW

**Comment by a3linux** [comment]
Is this a incompatible change with serverless 2.x and 3.x?
If so, I am not sure how do we control the release version of this plugin itself?

**Comment by steveperkins** [comment]
@a3linux  My thought was to either add a configuration that allows users to decide which resolver to use, or create a new v3-specific package so users can opt in to the resolver version they need to use. Thoughts?

**Comment by a3linux** [comment]
@steveperkins I am not sure. For NPM package, is it used to having new version not compatible with old one? How about ideas from other users of this plugin.

**Comment by steveperkins** [comment]
@a3linux It would probably be more difficult to maintain a v2-compatible version branch in addition to a v3-compatible version branch in the same repo/release plan. Some NPM users specify "Version X or higher" or "latest version" in their package.json and they'd have a harder time handling that change. We could create a separate NPM package that is v3-compatible so both can continue to be maintained with bugfixes and features. A configuration-based approach might make more sense than releasing a separate NPM package, though. We could probably make v3-compatible opt-in now to preserve backward-compatibility for v2 users and later switch v3 to be the default, once v2 is no longer supported or used.

**Comment by a3linux** [comment]
should be fine if we could have a option for v3 user as now and keep the v2 as default. 
Then we switch to v3 at the right time. 
I am not sure how to do that in JS, but this PR might not work like that.

**Comment by steveperkins** [comment]
@a3linux @wktk I took the general changes of this PR and created a new PR #6 that provides automatic support for v1, v2, and v3. The v1 and v3 variable resolvers use different syntax for registration, so the plugin can now register a slightly different handler for each version. The only real difference in resolution that affects this plugin is the fact that the v3 resolver now removes the "find:" prefix from the variable name string before providing it to the plugin. v3 also passes the name as an object instead of a string, expects an object as a return value, and doesn't support async function return values.

Please have a look and verify if this works for you. I tested by installing Serverless v1, running `sls package`, installing v2, running the same command, and installing v3 and running the command again. The .serverless file I used is just the AWS Node sample created with the `serverless` command, but referencing the plugin source and specifying a serverless-find-resource variable:

```
service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - ../serverless-find-resource
  
functions:
  hello:
    handler: handler.hello
    name: ${find:SecurityGroupId:skittles}-lambda
```

**Comment by wktk** [comment]
I’m sorry for my delayed response.  #6 works perfectly in my use case while keeping compatibility!

**Comment by steveperkins** [comment]
Excellent, thanks for confirming! I'll merge this PR and publish the new version to NPM.

**Comment by steveperkins** [comment]
Merged PR #6 and published v1.0.11 to NPM.

**Pull request closed without merging**
